/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CW1;

import org.junit.Test;
import static org.junit.Assert.*;

public class Dec2HexTest {
    @Test public void ValidateConverstion() {
        assertEquals("F", Dec2Hex.convert(new String[]{"15"}));
    }
}
